alter table public.equipment
  drop constraint if exists equipment_status_check;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.equipment'::regclass
      and conname = 'equipment_status_not_blank'
  ) then
    alter table public.equipment
      add constraint equipment_status_not_blank
      check (length(btrim(status)) > 0);
  end if;
end
$$;

create table if not exists public.inventory_options (
  id bigint generated by default as identity primary key,
  option_group text not null check (
    option_group in ('equipmentTypes', 'locations', 'statuses', 'equipmentNames')
  ),
  value text not null check (length(btrim(value)) > 0),
  value_key text generated always as (
    lower(regexp_replace(btrim(value), '\s+', ' ', 'g'))
  ) stored,
  created_at timestamptz not null default now(),
  unique (option_group, value_key)
);

alter table public.inventory_options enable row level security;

comment on table public.inventory_options is
  'User-managed additions to the inventory form controlled lists.';
