create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  status text not null check (length(btrim(status)) > 0),
  assigned_to text not null default '',
  display_name text not null,
  record_date date not null,
  category text not null,
  location text not null,
  pid text not null default 'n/a',
  mfg_part_number text not null default '',
  serial_number text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 10000),
  vendor text not null default '',
  notes text not null default ''
);

alter table public.equipment enable row level security;

comment on table public.equipment is
  'Equipment inventory accessed only through server-side application routes.';


create table if not exists public.inventory_options (
  id bigint generated by default as identity primary key,
  option_group text not null check (
    option_group in ('equipmentTypes', 'locations', 'statuses', 'equipmentNames')
  ),
  value text not null check (length(btrim(value)) > 0),
  value_key text generated always as (
    lower(regexp_replace(btrim(value), '\s+', ' ', 'g'))
  ) stored,
  created_at timestamptz not null default now(),
  unique (option_group, value_key)
);

alter table public.inventory_options enable row level security;

comment on table public.inventory_options is
  'User-managed additions to the inventory form controlled lists.';
