create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  status text not null check (length(btrim(status)) > 0),
  assigned_to text not null default '',
  display_name text not null,
  record_date date not null,
  category text not null,
  location text not null,
  pid text not null default 'n/a',
  mfg_part_number text not null default '',
  serial_number text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 10000),
  vendor text not null default '',
  notes text not null default ''
);

alter table public.equipment enable row level security;

comment on table public.equipment is
  'Equipment inventory accessed only through server-side application routes.';


create table if not exists public.inventory_options (
  id bigint generated by default as identity primary key,
  option_group text not null check (
    option_group in ('equipmentTypes', 'locations', 'statuses', 'equipmentNames')
  ),
  value text not null check (length(btrim(value)) > 0),
  value_key text generated always as (
    lower(regexp_replace(btrim(value), '\s+', ' ', 'g'))
  ) stored,
  created_at timestamptz not null default now(),
  unique (option_group, value_key)
);

alter table public.inventory_options enable row level security;

comment on table public.inventory_options is
  'User-managed additions to the inventory form controlled lists.';


create or replace function public.prevent_duplicate_equipment_serial()
returns trigger
language plpgsql
set search_path = public
as $
declare
  normalized_serial text;
begin
  normalized_serial := lower(regexp_replace(btrim(new.serial_number), '\\s+', ' ', 'g'));
  if normalized_serial = '' or normalized_serial in ('n/a', 'na', 'none') then
    return new;
  end if;

  if exists (
    select 1 from public.equipment
    where id is distinct from new.id
      and lower(regexp_replace(btrim(serial_number), '\\s+', ' ', 'g')) = normalized_serial
  ) then
    raise exception using
      errcode = '23505',
      message = 'An equipment record with this serial number already exists';
  end if;
  return new;
end;
$;

drop trigger if exists equipment_unique_serial on public.equipment;
create trigger equipment_unique_serial
before insert or update of serial_number on public.equipment
for each row execute function public.prevent_duplicate_equipment_serial();
