create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('available', 'infrastructure', 'checked-out')),
  assigned_to text not null default '',
  display_name text not null,
  record_date date not null,
  category text not null,
  location text not null,
  part_number text not null default '',
  serial_number text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 10000),
  vendor text not null default '',
  notes text not null default ''
);

alter table public.equipment enable row level security;

comment on table public.equipment is
  'Equipment inventory accessed only through server-side application routes.';
